In [41]:
import sys
sys.path.append('/Users/vikaspandey/my_projects/deeplearning_ai')
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import Binarizer

> __When the data is comprised with attributes of varying scale, many machine learning algorithms can benifit from rescaling the data to the same scale. This is called normalisation and the attributes are scaled between 0 and 1. The data can be rescaled using scikit-learn MinMaxScaler. This is useful for algorithms like gradient descent, neural networks, linear regression, k-nearest neighbours etc__

In [29]:
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv('../datasets/pima-indians-diabetes.csv', names=names)
X = data.loc[:, data.columns != 'class']
Y = data.loc[:, data.columns == 'class']

/Users/vikaspandey/miniconda2/envs/datascience/lib/python3.6/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [30]:
# Rescale Data
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(X)

/Users/vikaspandey/miniconda2/envs/datascience/lib/python3.6/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


> __Standardization is a process by which attributes are transformed with a gaussian distribution, differing means and standard deviation to a standard gaussian distribution with mean 0 and standard deviation 1. Data can be standardized by using StandardScaler. This is useful in techniques that assumes gaussian distribution of input variables and work better with scaled data such as linear regression, logistic regression and linear discriminate analysis.__

In [35]:
standard_scaler = StandardScaler()
standardized_data = standard_scaler.fit_transform(X)
standardized_data

/Users/vikaspandey/miniconda2/envs/datascience/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/vikaspandey/miniconda2/envs/datascience/lib/python3.6/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

> __Normalisation means rescaling each observation to have length 1. This can be done by using Normalize method of scikit-learn__

In [39]:
scaler = Normalizer()
normalised_X = scaler.fit_transform(X)
normalised_X

array([[0.03355237, 0.82762513, 0.40262844, ..., 0.18789327, 0.00350622,
        0.27960308],
       [0.008424  , 0.71604034, 0.55598426, ..., 0.22407851, 0.00295683,
        0.26114412],
       [0.04039768, 0.92409698, 0.32318146, ..., 0.11765825, 0.00339341,
        0.16159073],
       ...,
       [0.02691539, 0.65135243, 0.38758161, ..., 0.14103664, 0.00131885,
        0.16149234],
       [0.00665306, 0.83828547, 0.39918356, ..., 0.20025708, 0.00232192,
        0.31269379],
       [0.00791454, 0.73605211, 0.55401772, ..., 0.24060198, 0.00249308,
        0.18203439]])

> __Binarizing data means transforming data using threshold. All the data below taht threshould will be marked as 0 and above will be marked as 1__

In [45]:
b = Binarizer(threshold=0.11)
b_data = b.fit_transform(X)
b_data

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

### Data Smoothening Methods