In [30]:
%load_ext nb_black
import numpy as np

<IPython.core.display.Javascript object>

In [3]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(5,)

In [9]:
# Multinested array
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,6,8,9]

arr = np.array([my_lst1, my_lst2, my_lst3])

In [10]:
arr.shape

(3, 5)

In [11]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [12]:
arr.shape

(3, 5)

### Indexing

In [14]:
arr[:,:] # -- rows,col

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [16]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [17]:
arr = np.arange(0, 10, step=2)

In [18]:
arr

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(1,10,50)  # 50 points between 1 to 10. These points are equallly spaced

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [23]:
### Some condition useful in EDA

val = 2
arr[arr < 2]

array([0])

In [24]:
## Random Distribution
np.random.rand(3,3)

array([[0.1178633 , 0.60359722, 0.19207483],
       [0.5591231 , 0.15160123, 0.98879258],
       [0.26357589, 0.69971071, 0.57193008]])

In [25]:
arr_ex = np.random.randn(4,4)

In [26]:
arr_ex

array([[-0.37223962, -0.99784687,  0.709156  , -0.07110843],
       [ 0.32832894,  2.55840274, -0.76825588, -0.19175444],
       [ 0.01542666,  0.25083128,  0.12377631,  0.04391607],
       [-0.01758376,  0.38686953,  0.14163779, -1.52268014]])

#### Pandas Tutorial

In [29]:
import pandas as pd
import numpy as np

In [32]:
df = pd.DataFrame(
    np.arange(0, 20).reshape(5, 4),
    index=["Row1", "Row2", "Row3", "Row4", "Row5"],
    columns=["Column1", "Column2", "Column3", "Column4"],
)

<IPython.core.display.Javascript object>

In [33]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

<IPython.core.display.Javascript object>

In [37]:
## Accessing the elements
# 1. .loc 2. .iloc
type(df.loc["Row1"]) # Type will be Series when selecting only one row

pandas.core.series.Series

<IPython.core.display.Javascript object>

In [41]:
df.iloc[0:2, 0:2] # Type will be dataframe

Column1  Column2
Row1        0        1
Row2        4        5

<IPython.core.display.Javascript object>

In [42]:
df.iloc[:, 1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

<IPython.core.display.Javascript object>

In [43]:
df.iloc[:, 1:].values.shape

(5, 3)

<IPython.core.display.Javascript object>

In [44]:
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

<IPython.core.display.Javascript object>

In [45]:
df["Column1"].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: Column1, dtype: int64

<IPython.core.display.Javascript object>

In [46]:
df["Column1"].unique()

array([ 0,  4,  8, 12, 16])

<IPython.core.display.Javascript object>

In [47]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

<IPython.core.display.Javascript object>

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 360.0+ bytes


<IPython.core.display.Javascript object>

In [49]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

<IPython.core.display.Javascript object>